### PR TITLE
Fix captions for 02 and 05

### PR DESCRIPTION
**Pull request by sjsrey**
After this is merged, chapters 02 and 05 figures can be changed as long as metadata is edited (if needed).

### CODE REVIEW

**Comment by darribas** [comment]
This looks OK, there's an HTML file changed and the Makefile too. Are those intentional? The Makefile I think we should leave it as it was and, if necessary, add a new command?

**Comment by sjsrey** [comment]
> This looks OK, there's an HTML file changed and the Makefile too. Are those intentional? The Makefile I think we should leave it as it was and, if necessary, add a new command?

I will fix the pr once I'm done with the other chapter captions. Thanks for catching!

**Comment by sjsrey** [comment]
This is ready to go with regards to all the captions.

Note I kept the makefile change as I can't run the lab locally without `NB_UID=1000`

**Comment by ljwolf** [comment]
Great, OK. I've been making makefile changes locally & not propagating them (since GIDs and UIDs will vary across platforms) but I'm OK with propagating this for now. 

It looks clean to me!

**Comment by darribas** [comment]
I think we should come up with a more general solution for the `NB_UID`. I _think_ `NB_UID=$UID` should work across setup's. I'll investigate and update the `Makefile`

**Pull request merged**
