### PR TITLE
Review of CH03: Spatial Data Processing

### PR DESCRIPTION
**Pull request by ljwolf**
In a few places, I've removed comments and added justification to address their content. 
There was only one question at the end. I've added four more.

### CODE REVIEW

**Comment by ljwolf** [comment]
To see the line-by-line diff, inspect 1d3c4e9

**Review by sjsrey — APPROVED** [review]

**Comment by darribas** [comment]
Somehow it doesn't let me see the main changes on your end, it's all adding the new file and removing the old one?

**Comment by ljwolf** [comment]
Hmm, now there is a merge conflict. This was not the case when the edits were submitted. I will try to address this. 

To see the main changes, view the first commit (1d3c4e9). You can click that in this text, or click the commit hash above

Screenshot from 2021-01-14 11-29-32

**Comment by ljwolf** [comment]
OK, I have re-based my changes onto the current master.

**Pull request merged**
