### PR TITLE
Tooling for increasing dpi

### PR DESCRIPTION
**Pull request by sjsrey**
- inject dpi bump in the notebooks prior to latex build (resource files are ignored with inline for dpi setting)
- fix missing crs in 09

### CODE REVIEW

**Comment by sjsrey** [comment]
We should tag after merging as I sent Lara the pdf that I built locally off of this.

**Comment by darribas** [comment]
I removed the `crs` last week because the file that is checked in at the repo now is not on `4326` and comes w/ CRS info, no?

**Comment by sjsrey** [comment]
When I tried to run this locally it complained about no crs, so that is why I added it back in.

Yah, the docs are a pain, I don't know why they got included.

**Comment by darribas** [comment]
I always run `make reset_docs` before commit: 

https://github.com/gdsbook/book/blob/38d7c504e87eda0f76c3e531b1e1dfab526b98fc/Makefile#L49-L52

On the file, I'm seeing now a different CRS?

```python
In [2]: db = geopandas.read_file("https://github.com/gdsbook/book/raw/master/data/us_county_income/uscountypcincome.gpkg
   ...: ")

In [3]: db.crs
Out[3]:
<Geographic 2D CRS: GEOGCS["Undefined geographic SRS",DATUM["unknown", ...>
Name: Undefined geographic SRS
Axis Info [ellipsoidal]:
- lat[north]: Latitude (degree)
- lon[east]: Longitude (degree)
Area of Use:
- undefined
Datum: unknown
- Ellipsoid: unknown
- Prime Meridian: Greenwich

In [4]:
```

This is what I found last week which prompted the change?

**Comment by sjsrey** [comment]
I'm running this in the container:

image

**Comment by sjsrey** [comment]
The nb is not pulling from the remote:

image

What do you see if you load the local geopackage?

**Comment by ljwolf** [comment]
When I run the spatial inequality notebook from *within* the docker, I get the error @sjsrey documents. When I load the geopackage *outside* of the docker, I have no issue. I think this suggests a Proj version issue within the docker?

**Comment by darribas** [comment]
What version of the container are you using? I'm on `darribas/gds_dev:7.0` and encounter no issue?

**Comment by sjsrey** [comment]
We are on [6.1](https://github.com/gdsbook/book/blob/master/Makefile#L11)

**Comment by sjsrey** [comment]
If I update the image to 7.0, all is good, so I think @ljwolf has the correct diagnosis of the issue.

Should we update the Makefile to use 7.0? If yes, I can close this and reissue a clean PR that includes that and the DPI changes (without the doc noise).

**Comment by sjsrey** [comment]
This should now be good to go (docs removed).

**Comment by darribas** [comment]
> Should we update the Makefile to use 7.0? If yes, I can close this and reissue a clean PR that includes that and the DPI changes (without the doc noise).

Yeah, I'd say so. I was holding off because the jupyterbook build was pinned to an older version, but it's now migrated (as of last week).

Serge, I think you must have the HTML build turned on at your fork because there're commits from the bot to this PR and there're file changes in `docs` again (I was guilty of this at some point too!). Might be worth checking and, if so, disabling?

**Comment by sjsrey** [comment]
Moved to #249

**Pull request closed without merging**
