### PR TITLE
Use remote read of geopackage for Inequality chapter

### PR DESCRIPTION
**Pull request by sjsrey**
This cleans up the construction of the inequality chapter data and moves all the reads to use remote files rather than local files.

Using parquet is problematic as I couldn't get the depedencies added to our environment.

### CODE REVIEW

**Comment by darribas** [comment]
Let's discuss it on the next call, but my preference would be to keep all the data the book relies on (ie. clean versions) in the repo. This makes it cleaner for testing, but also easier to deploy with bad connectivity (e.g. workshops on hotels with bad WiFi). Maybe we can have a look at the construction and come up with a more efficient storage of the data that makes it fit on the repo?

All the other datasets are documented on a single notebook that goes from original source to the final file we use. There might be reasons for not doing this, but if not I'd also vote for aligning this dataset with the rest in the book.

> Using parquet is problematic as I couldn't get the depedencies added to our environment.

The book runs on [`gds_env:5.0`](https://github.com/darribas/gds_env/releases/tag/v5.0) and I'll make sure going forward it runs on subsequent versions as much as possible. This includes out-of-the-box all dependencies to read/write (geo-)parquet. What environment do you mean?

**Comment by darribas** [comment]
[Mental note this also made me think we do use some remote datasets from `osmnx` in Feature Eng, for example. It'd be good to have a back up saved on the repo and an alternative box note like [here](https://darribas.org/gds_course/content/bB/lab_B.html#dataset) that doesn't *run* but shows the code to run it locally]

**Comment by ljwolf** [comment]
We also use osmnx in the text of ch. 3

**Comment by sjsrey** [comment]
This is now rolled into #118

**Pull request closed without merging**
